AWSTemplateFormatVersion: 2010-09-09
Description: APIGateway Template for aws portfolio

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio-suzuki
    Description: Project name for tagging and resource naming

  CORSAllowOrigins:
    Type: String
    Description: CORSAllow Origins name for static hosting

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  APIGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-apigateway"
      Tags:
        Name: !Sub "${ProjectName}-${Environment}"
        Environment: !Ref Environment
      ProtocolType: HTTP
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders:
          - Content-Type
          - authorization
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowOrigins:
          - !Ref CORSAllowOrigins
        MaxAge: 3600

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref APIGateway
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: 2.0
      TimeoutInMillis: 30000
      IntegrationUri: !ImportValue portfolio-suzuki-prod-Lambda

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref APIGateway
      StageName: prod
      AutoDeploy: true

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGateway
      RouteKey: POST /api/sns
      AuthorizationType: NONE
      Target: !Join ['/', ['integrations', !Ref Integration]]

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Outputs:
  ApiGatewayExecuteArn:
    Value: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*/*"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-apigateway-execute-arn"

  ApiDomainName:
    Description: API Gateway domain name for CloudFront origin
    Value: !Select
      - 1
      - !Split
        - "https://"
        - !GetAtt APIGateway.ApiEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-apigateway-domain"
