AWSTemplateFormatVersion: 2010-09-09
Description:  Lambda Template for aws pricing

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio-suzuki

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  Lambda:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-Lambda"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-Lambda"
        - Key: Environment
          Value: !Ref Environment
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Role: !ImportValue portfolio-suzuki-prod-lambda-sns-role
      Timeout: 3
      MemorySize: 128
      EphemeralStorage:
        Size: 512
      Code:
        S3Bucket: suzu-cf-template
        S3Key: LambdaZIP/portfolio-suzuki/lambda_function.zip

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !ImportValue portfolio-suzuki-prod-apigateway-execute-arn

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  LambdaArn:
    Value: !GetAtt Lambda.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-Lambda"