AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Template for aws portfolio
# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio-suzuki
    Description: Project name for tagging and resource naming

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

  DomainName:
    Type: String
    Description: Main domain name

  ACMCertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_100

        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"

        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        Origins:
          - Id: S3Origin
            DomainName: !ImportValue portfolio-suzuki-S3
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CloudFrontOAC

          - Id: APIGatewayOrigin
            DomainName: !ImportValue portfolio-suzuki-prod-apigateway-domain
            OriginPath: "/prod"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false

        CacheBehaviors:
          - PathPattern: "/api/*"
            TargetOriginId: APIGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !Ref ApiCachePolicy
            OriginRequestPolicyId: !Ref ApiOriginRequestPolicy

        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /403.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponsePagePath: /404.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0

  ApiOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub "${ProjectName}-${Environment}-OriginRequestPolicy"
        Comment: Forward all headers except Host, no query strings
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Content-Type
        CookiesConfig:
          CookieBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: none

  ApiCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${ProjectName}-${Environment}-CachePolicy"
        DefaultTTL: 0
        MinTTL: 0
        MaxTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: false
          EnableAcceptEncodingBrotli: false
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-${Environment}-oac"
        SigningProtocol: sigv4
        SigningBehavior: always
        OriginAccessControlOriginType: s3

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  CloudFrontDistribution:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${ProjectName}-CloudFront"

  CloudFrontDistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${ProjectName}-CloudFront-DomainName"