AWSTemplateFormatVersion: '2010-09-09'
Description: Route53 Template for aws portfolio

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: portfolio-suzuki
    Description: Project name for tagging and resource naming

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

  DomainName:
    Type: String
    Description: Main domain name

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  ###Route53HostedZone###
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: Hosted zone for portfolio

  ###Route53ARecord###
  ARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !ImportValue portfolio-suzuki-CloudFront-DomainName
        HostedZoneId: Z2FDTNDATAQYW2