AWSTemplateFormatVersion: 2010-09-09
Description: IAM Template for AWSIoT-demo

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: AWSIoT-demo

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  EC2Role:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-ec2-role"
      Path: "/"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}"
        - Key: Environment
          Value: !Ref Environment

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

      Policies:
        - PolicyName: AllowS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::suzu-cf-template

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::suzu-cf-template/*

  IoTRuleRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-iot-rule-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBPutItem
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !ImportValue AWSIoT-demo-prod-sensor-data-arn

  LambdaRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-lambda-role"
      Path: "/"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}"
        - Key: Environment
          Value: !Ref Environment

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: CloudWatchPutMetric
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"


# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  EC2Role:
    Value: !Ref EC2Role
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ec2-role"

  IoTRuleRoleArn:
    Value: !GetAtt IoTRuleRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-iot-rule-role-Arn"

  LambdaRoleArn:
    Value: !GetAtt LambdaRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-Lambda-role-Arn"