AWSTemplateFormatVersion: 2010-09-09
Description: CloudWatch Template for AWSIoT-demo

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
    Default: AWSIoT-demo

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

# ------------------------------------------------------------
# Resources
# ------------------------------------------------------------
Resources:
  CloudWatchDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${ProjectName}-${Environment}-iot-dashboard"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "text",
              "x": 0,
              "y": 0,
              "width": 24,
              "height": 2,
              "properties": {
                "markdown": "## AWS IoT Demo Alert Dashboard\n異常検知の可視化"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 2,
              "width": 24,
              "height": 6,
              "properties": {
                "metrics": [
                  [
                    {
                      "expression": "SEARCH('{sensor_simulator,Environment,DeviceId,Location} MetricName=\"high_temperature\" Environment=\"${Environment}\"', 'Sum', 300)"
                    }
                  ],
                  [
                    {
                      "expression": "SEARCH('{sensor_simulator,Environment,DeviceId,Location} MetricName=\"high_co2\" Environment=\"${Environment}\"', 'Sum', 300)"
                    }
                  ],
                  [
                    {
                      "expression": "SEARCH('{sensor_simulator,Environment,DeviceId,Location} MetricName=\"low_battery\" Environment=\"${Environment}\"', 'Sum', 300)"
                    }
                  ]
                ],
                "region": "${AWS::Region}",
                "stat": "Sum",
                "period": 300,
                "title": "Alert Types"
              }
            }
          ]
        }
